server:
  port: 3000
spring:
  application:
    name: redis-provider
  redis:
    cluster:
      nodes: 149.248.18.111:9920,149.248.18.111:9921,149.248.18.111:9922,149.248.18.111:9923,149.248.18.111:9924,149.248.18.111:9925
      max-redirects: 3
    password: justin.171464928
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://45.32.64.240:8761/eureka/
  instance:
    prefer-ip-address: true