server:
  port: 5000
spring:
  application:
    name: project-manager
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
oss:
  endpoint: oss-us-west-1.aliyuncs.com
  accessKeyId: LTAI4FcBhdDymSvgNUX3AnmD
  accessKeySecret: yi2PLWM5fia6uzWO5To3xZpTkoDuSv
  bucketName: capharnaum