server:
  port: 6100
spring:
  application:
    name: oss-provider
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
rocketmq:
  name-server: 45.76.175.197:19876;45.76.175.197:29876
  consumer:
    group: ChunkFileUploadGroup
oss:
  endpoint: oss-us-west-1.aliyuncs.com
  accessKeyId: LTAI4FcBhdDymSvgNUX3AnmD
  accessKeySecret: yi2PLWM5fia6uzWO5To3xZpTkoDuSv
  bucketName: capharnaum