package com.crowdFunding.databaseProvider.model;

public class InitiatorInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column initiator_info.id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column initiator_info.user_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column initiator_info.pay_number
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private String payNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column initiator_info.id_number
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private String idNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column initiator_info.id
     *
     * @return the value of initiator_info.id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column initiator_info.id
     *
     * @param id the value for initiator_info.id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column initiator_info.user_id
     *
     * @return the value of initiator_info.user_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column initiator_info.user_id
     *
     * @param userId the value for initiator_info.user_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column initiator_info.pay_number
     *
     * @return the value of initiator_info.pay_number
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public String getPayNumber() {
        return payNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column initiator_info.pay_number
     *
     * @param payNumber the value for initiator_info.pay_number
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setPayNumber(String payNumber) {
        this.payNumber = payNumber == null ? null : payNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column initiator_info.id_number
     *
     * @return the value of initiator_info.id_number
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column initiator_info.id_number
     *
     * @param idNumber the value for initiator_info.id_number
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }
}