package com.crowdFunding.databaseProvider.model;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.project_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_name
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_position
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private String memberPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_introduction
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private String memberIntroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_avatar
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private String memberAvatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.project_id
     *
     * @return the value of member.project_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.project_id
     *
     * @param projectId the value for member.project_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_name
     *
     * @return the value of member.member_name
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_name
     *
     * @param memberName the value for member.member_name
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_position
     *
     * @return the value of member.member_position
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public String getMemberPosition() {
        return memberPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_position
     *
     * @param memberPosition the value for member.member_position
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setMemberPosition(String memberPosition) {
        this.memberPosition = memberPosition == null ? null : memberPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_introduction
     *
     * @return the value of member.member_introduction
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public String getMemberIntroduction() {
        return memberIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_introduction
     *
     * @param memberIntroduction the value for member.member_introduction
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setMemberIntroduction(String memberIntroduction) {
        this.memberIntroduction = memberIntroduction == null ? null : memberIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_avatar
     *
     * @return the value of member.member_avatar
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public String getMemberAvatar() {
        return memberAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_avatar
     *
     * @param memberAvatar the value for member.member_avatar
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setMemberAvatar(String memberAvatar) {
        this.memberAvatar = memberAvatar == null ? null : memberAvatar.trim();
    }
}