package com.crowdFunding.databaseProvider.model;

import java.util.ArrayList;
import java.util.List;

public class ProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public ProjectExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionIsNull() {
            addCriterion("main_description is null");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionIsNotNull() {
            addCriterion("main_description is not null");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionEqualTo(String value) {
            addCriterion("main_description =", value, "mainDescription");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionNotEqualTo(String value) {
            addCriterion("main_description <>", value, "mainDescription");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionGreaterThan(String value) {
            addCriterion("main_description >", value, "mainDescription");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("main_description >=", value, "mainDescription");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionLessThan(String value) {
            addCriterion("main_description <", value, "mainDescription");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionLessThanOrEqualTo(String value) {
            addCriterion("main_description <=", value, "mainDescription");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionLike(String value) {
            addCriterion("main_description like", value, "mainDescription");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionNotLike(String value) {
            addCriterion("main_description not like", value, "mainDescription");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionIn(List<String> values) {
            addCriterion("main_description in", values, "mainDescription");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionNotIn(List<String> values) {
            addCriterion("main_description not in", values, "mainDescription");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionBetween(String value1, String value2) {
            addCriterion("main_description between", value1, value2, "mainDescription");
            return (Criteria) this;
        }

        public Criteria andMainDescriptionNotBetween(String value1, String value2) {
            addCriterion("main_description not between", value1, value2, "mainDescription");
            return (Criteria) this;
        }

        public Criteria andHighlightIsNull() {
            addCriterion("highlight is null");
            return (Criteria) this;
        }

        public Criteria andHighlightIsNotNull() {
            addCriterion("highlight is not null");
            return (Criteria) this;
        }

        public Criteria andHighlightEqualTo(String value) {
            addCriterion("highlight =", value, "highlight");
            return (Criteria) this;
        }

        public Criteria andHighlightNotEqualTo(String value) {
            addCriterion("highlight <>", value, "highlight");
            return (Criteria) this;
        }

        public Criteria andHighlightGreaterThan(String value) {
            addCriterion("highlight >", value, "highlight");
            return (Criteria) this;
        }

        public Criteria andHighlightGreaterThanOrEqualTo(String value) {
            addCriterion("highlight >=", value, "highlight");
            return (Criteria) this;
        }

        public Criteria andHighlightLessThan(String value) {
            addCriterion("highlight <", value, "highlight");
            return (Criteria) this;
        }

        public Criteria andHighlightLessThanOrEqualTo(String value) {
            addCriterion("highlight <=", value, "highlight");
            return (Criteria) this;
        }

        public Criteria andHighlightLike(String value) {
            addCriterion("highlight like", value, "highlight");
            return (Criteria) this;
        }

        public Criteria andHighlightNotLike(String value) {
            addCriterion("highlight not like", value, "highlight");
            return (Criteria) this;
        }

        public Criteria andHighlightIn(List<String> values) {
            addCriterion("highlight in", values, "highlight");
            return (Criteria) this;
        }

        public Criteria andHighlightNotIn(List<String> values) {
            addCriterion("highlight not in", values, "highlight");
            return (Criteria) this;
        }

        public Criteria andHighlightBetween(String value1, String value2) {
            addCriterion("highlight between", value1, value2, "highlight");
            return (Criteria) this;
        }

        public Criteria andHighlightNotBetween(String value1, String value2) {
            addCriterion("highlight not between", value1, value2, "highlight");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(Long value) {
            addCriterion("money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(Long value) {
            addCriterion("money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(Long value) {
            addCriterion("money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(Long value) {
            addCriterion("money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(Long value) {
            addCriterion("money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(Long value) {
            addCriterion("money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<Long> values) {
            addCriterion("money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<Long> values) {
            addCriterion("money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(Long value1, Long value2) {
            addCriterion("money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(Long value1, Long value2) {
            addCriterion("money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andDayIsNull() {
            addCriterion("day is null");
            return (Criteria) this;
        }

        public Criteria andDayIsNotNull() {
            addCriterion("day is not null");
            return (Criteria) this;
        }

        public Criteria andDayEqualTo(Byte value) {
            addCriterion("day =", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotEqualTo(Byte value) {
            addCriterion("day <>", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayGreaterThan(Byte value) {
            addCriterion("day >", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayGreaterThanOrEqualTo(Byte value) {
            addCriterion("day >=", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLessThan(Byte value) {
            addCriterion("day <", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLessThanOrEqualTo(Byte value) {
            addCriterion("day <=", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayIn(List<Byte> values) {
            addCriterion("day in", values, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotIn(List<Byte> values) {
            addCriterion("day not in", values, "day");
            return (Criteria) this;
        }

        public Criteria andDayBetween(Byte value1, Byte value2) {
            addCriterion("day between", value1, value2, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotBetween(Byte value1, Byte value2) {
            addCriterion("day not between", value1, value2, "day");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andReturnPurchaseIsNull() {
            addCriterion("return_purchase is null");
            return (Criteria) this;
        }

        public Criteria andReturnPurchaseIsNotNull() {
            addCriterion("return_purchase is not null");
            return (Criteria) this;
        }

        public Criteria andReturnPurchaseEqualTo(Byte value) {
            addCriterion("return_purchase =", value, "returnPurchase");
            return (Criteria) this;
        }

        public Criteria andReturnPurchaseNotEqualTo(Byte value) {
            addCriterion("return_purchase <>", value, "returnPurchase");
            return (Criteria) this;
        }

        public Criteria andReturnPurchaseGreaterThan(Byte value) {
            addCriterion("return_purchase >", value, "returnPurchase");
            return (Criteria) this;
        }

        public Criteria andReturnPurchaseGreaterThanOrEqualTo(Byte value) {
            addCriterion("return_purchase >=", value, "returnPurchase");
            return (Criteria) this;
        }

        public Criteria andReturnPurchaseLessThan(Byte value) {
            addCriterion("return_purchase <", value, "returnPurchase");
            return (Criteria) this;
        }

        public Criteria andReturnPurchaseLessThanOrEqualTo(Byte value) {
            addCriterion("return_purchase <=", value, "returnPurchase");
            return (Criteria) this;
        }

        public Criteria andReturnPurchaseIn(List<Byte> values) {
            addCriterion("return_purchase in", values, "returnPurchase");
            return (Criteria) this;
        }

        public Criteria andReturnPurchaseNotIn(List<Byte> values) {
            addCriterion("return_purchase not in", values, "returnPurchase");
            return (Criteria) this;
        }

        public Criteria andReturnPurchaseBetween(Byte value1, Byte value2) {
            addCriterion("return_purchase between", value1, value2, "returnPurchase");
            return (Criteria) this;
        }

        public Criteria andReturnPurchaseNotBetween(Byte value1, Byte value2) {
            addCriterion("return_purchase not between", value1, value2, "returnPurchase");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryIsNull() {
            addCriterion("crowd_funding_story is null");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryIsNotNull() {
            addCriterion("crowd_funding_story is not null");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryEqualTo(String value) {
            addCriterion("crowd_funding_story =", value, "crowdFundingStory");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryNotEqualTo(String value) {
            addCriterion("crowd_funding_story <>", value, "crowdFundingStory");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryGreaterThan(String value) {
            addCriterion("crowd_funding_story >", value, "crowdFundingStory");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryGreaterThanOrEqualTo(String value) {
            addCriterion("crowd_funding_story >=", value, "crowdFundingStory");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryLessThan(String value) {
            addCriterion("crowd_funding_story <", value, "crowdFundingStory");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryLessThanOrEqualTo(String value) {
            addCriterion("crowd_funding_story <=", value, "crowdFundingStory");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryLike(String value) {
            addCriterion("crowd_funding_story like", value, "crowdFundingStory");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryNotLike(String value) {
            addCriterion("crowd_funding_story not like", value, "crowdFundingStory");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryIn(List<String> values) {
            addCriterion("crowd_funding_story in", values, "crowdFundingStory");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryNotIn(List<String> values) {
            addCriterion("crowd_funding_story not in", values, "crowdFundingStory");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryBetween(String value1, String value2) {
            addCriterion("crowd_funding_story between", value1, value2, "crowdFundingStory");
            return (Criteria) this;
        }

        public Criteria andCrowdFundingStoryNotBetween(String value1, String value2) {
            addCriterion("crowd_funding_story not between", value1, value2, "crowdFundingStory");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingIsNull() {
            addCriterion("why_crowd_funding is null");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingIsNotNull() {
            addCriterion("why_crowd_funding is not null");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingEqualTo(String value) {
            addCriterion("why_crowd_funding =", value, "whyCrowdFunding");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingNotEqualTo(String value) {
            addCriterion("why_crowd_funding <>", value, "whyCrowdFunding");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingGreaterThan(String value) {
            addCriterion("why_crowd_funding >", value, "whyCrowdFunding");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingGreaterThanOrEqualTo(String value) {
            addCriterion("why_crowd_funding >=", value, "whyCrowdFunding");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingLessThan(String value) {
            addCriterion("why_crowd_funding <", value, "whyCrowdFunding");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingLessThanOrEqualTo(String value) {
            addCriterion("why_crowd_funding <=", value, "whyCrowdFunding");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingLike(String value) {
            addCriterion("why_crowd_funding like", value, "whyCrowdFunding");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingNotLike(String value) {
            addCriterion("why_crowd_funding not like", value, "whyCrowdFunding");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingIn(List<String> values) {
            addCriterion("why_crowd_funding in", values, "whyCrowdFunding");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingNotIn(List<String> values) {
            addCriterion("why_crowd_funding not in", values, "whyCrowdFunding");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingBetween(String value1, String value2) {
            addCriterion("why_crowd_funding between", value1, value2, "whyCrowdFunding");
            return (Criteria) this;
        }

        public Criteria andWhyCrowdFundingNotBetween(String value1, String value2) {
            addCriterion("why_crowd_funding not between", value1, value2, "whyCrowdFunding");
            return (Criteria) this;
        }

        public Criteria andCompanyFileIsNull() {
            addCriterion("company_file is null");
            return (Criteria) this;
        }

        public Criteria andCompanyFileIsNotNull() {
            addCriterion("company_file is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyFileEqualTo(String value) {
            addCriterion("company_file =", value, "companyFile");
            return (Criteria) this;
        }

        public Criteria andCompanyFileNotEqualTo(String value) {
            addCriterion("company_file <>", value, "companyFile");
            return (Criteria) this;
        }

        public Criteria andCompanyFileGreaterThan(String value) {
            addCriterion("company_file >", value, "companyFile");
            return (Criteria) this;
        }

        public Criteria andCompanyFileGreaterThanOrEqualTo(String value) {
            addCriterion("company_file >=", value, "companyFile");
            return (Criteria) this;
        }

        public Criteria andCompanyFileLessThan(String value) {
            addCriterion("company_file <", value, "companyFile");
            return (Criteria) this;
        }

        public Criteria andCompanyFileLessThanOrEqualTo(String value) {
            addCriterion("company_file <=", value, "companyFile");
            return (Criteria) this;
        }

        public Criteria andCompanyFileLike(String value) {
            addCriterion("company_file like", value, "companyFile");
            return (Criteria) this;
        }

        public Criteria andCompanyFileNotLike(String value) {
            addCriterion("company_file not like", value, "companyFile");
            return (Criteria) this;
        }

        public Criteria andCompanyFileIn(List<String> values) {
            addCriterion("company_file in", values, "companyFile");
            return (Criteria) this;
        }

        public Criteria andCompanyFileNotIn(List<String> values) {
            addCriterion("company_file not in", values, "companyFile");
            return (Criteria) this;
        }

        public Criteria andCompanyFileBetween(String value1, String value2) {
            addCriterion("company_file between", value1, value2, "companyFile");
            return (Criteria) this;
        }

        public Criteria andCompanyFileNotBetween(String value1, String value2) {
            addCriterion("company_file not between", value1, value2, "companyFile");
            return (Criteria) this;
        }

        public Criteria andTeamFileIsNull() {
            addCriterion("team_file is null");
            return (Criteria) this;
        }

        public Criteria andTeamFileIsNotNull() {
            addCriterion("team_file is not null");
            return (Criteria) this;
        }

        public Criteria andTeamFileEqualTo(String value) {
            addCriterion("team_file =", value, "teamFile");
            return (Criteria) this;
        }

        public Criteria andTeamFileNotEqualTo(String value) {
            addCriterion("team_file <>", value, "teamFile");
            return (Criteria) this;
        }

        public Criteria andTeamFileGreaterThan(String value) {
            addCriterion("team_file >", value, "teamFile");
            return (Criteria) this;
        }

        public Criteria andTeamFileGreaterThanOrEqualTo(String value) {
            addCriterion("team_file >=", value, "teamFile");
            return (Criteria) this;
        }

        public Criteria andTeamFileLessThan(String value) {
            addCriterion("team_file <", value, "teamFile");
            return (Criteria) this;
        }

        public Criteria andTeamFileLessThanOrEqualTo(String value) {
            addCriterion("team_file <=", value, "teamFile");
            return (Criteria) this;
        }

        public Criteria andTeamFileLike(String value) {
            addCriterion("team_file like", value, "teamFile");
            return (Criteria) this;
        }

        public Criteria andTeamFileNotLike(String value) {
            addCriterion("team_file not like", value, "teamFile");
            return (Criteria) this;
        }

        public Criteria andTeamFileIn(List<String> values) {
            addCriterion("team_file in", values, "teamFile");
            return (Criteria) this;
        }

        public Criteria andTeamFileNotIn(List<String> values) {
            addCriterion("team_file not in", values, "teamFile");
            return (Criteria) this;
        }

        public Criteria andTeamFileBetween(String value1, String value2) {
            addCriterion("team_file between", value1, value2, "teamFile");
            return (Criteria) this;
        }

        public Criteria andTeamFileNotBetween(String value1, String value2) {
            addCriterion("team_file not between", value1, value2, "teamFile");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andGmtDeployIsNull() {
            addCriterion("gmt_deploy is null");
            return (Criteria) this;
        }

        public Criteria andGmtDeployIsNotNull() {
            addCriterion("gmt_deploy is not null");
            return (Criteria) this;
        }

        public Criteria andGmtDeployEqualTo(Long value) {
            addCriterion("gmt_deploy =", value, "gmtDeploy");
            return (Criteria) this;
        }

        public Criteria andGmtDeployNotEqualTo(Long value) {
            addCriterion("gmt_deploy <>", value, "gmtDeploy");
            return (Criteria) this;
        }

        public Criteria andGmtDeployGreaterThan(Long value) {
            addCriterion("gmt_deploy >", value, "gmtDeploy");
            return (Criteria) this;
        }

        public Criteria andGmtDeployGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_deploy >=", value, "gmtDeploy");
            return (Criteria) this;
        }

        public Criteria andGmtDeployLessThan(Long value) {
            addCriterion("gmt_deploy <", value, "gmtDeploy");
            return (Criteria) this;
        }

        public Criteria andGmtDeployLessThanOrEqualTo(Long value) {
            addCriterion("gmt_deploy <=", value, "gmtDeploy");
            return (Criteria) this;
        }

        public Criteria andGmtDeployIn(List<Long> values) {
            addCriterion("gmt_deploy in", values, "gmtDeploy");
            return (Criteria) this;
        }

        public Criteria andGmtDeployNotIn(List<Long> values) {
            addCriterion("gmt_deploy not in", values, "gmtDeploy");
            return (Criteria) this;
        }

        public Criteria andGmtDeployBetween(Long value1, Long value2) {
            addCriterion("gmt_deploy between", value1, value2, "gmtDeploy");
            return (Criteria) this;
        }

        public Criteria andGmtDeployNotBetween(Long value1, Long value2) {
            addCriterion("gmt_deploy not between", value1, value2, "gmtDeploy");
            return (Criteria) this;
        }

        public Criteria andFundMoneyIsNull() {
            addCriterion("fund_money is null");
            return (Criteria) this;
        }

        public Criteria andFundMoneyIsNotNull() {
            addCriterion("fund_money is not null");
            return (Criteria) this;
        }

        public Criteria andFundMoneyEqualTo(Long value) {
            addCriterion("fund_money =", value, "fundMoney");
            return (Criteria) this;
        }

        public Criteria andFundMoneyNotEqualTo(Long value) {
            addCriterion("fund_money <>", value, "fundMoney");
            return (Criteria) this;
        }

        public Criteria andFundMoneyGreaterThan(Long value) {
            addCriterion("fund_money >", value, "fundMoney");
            return (Criteria) this;
        }

        public Criteria andFundMoneyGreaterThanOrEqualTo(Long value) {
            addCriterion("fund_money >=", value, "fundMoney");
            return (Criteria) this;
        }

        public Criteria andFundMoneyLessThan(Long value) {
            addCriterion("fund_money <", value, "fundMoney");
            return (Criteria) this;
        }

        public Criteria andFundMoneyLessThanOrEqualTo(Long value) {
            addCriterion("fund_money <=", value, "fundMoney");
            return (Criteria) this;
        }

        public Criteria andFundMoneyIn(List<Long> values) {
            addCriterion("fund_money in", values, "fundMoney");
            return (Criteria) this;
        }

        public Criteria andFundMoneyNotIn(List<Long> values) {
            addCriterion("fund_money not in", values, "fundMoney");
            return (Criteria) this;
        }

        public Criteria andFundMoneyBetween(Long value1, Long value2) {
            addCriterion("fund_money between", value1, value2, "fundMoney");
            return (Criteria) this;
        }

        public Criteria andFundMoneyNotBetween(Long value1, Long value2) {
            addCriterion("fund_money not between", value1, value2, "fundMoney");
            return (Criteria) this;
        }

        public Criteria andSupporterNumberIsNull() {
            addCriterion("supporter_number is null");
            return (Criteria) this;
        }

        public Criteria andSupporterNumberIsNotNull() {
            addCriterion("supporter_number is not null");
            return (Criteria) this;
        }

        public Criteria andSupporterNumberEqualTo(Integer value) {
            addCriterion("supporter_number =", value, "supporterNumber");
            return (Criteria) this;
        }

        public Criteria andSupporterNumberNotEqualTo(Integer value) {
            addCriterion("supporter_number <>", value, "supporterNumber");
            return (Criteria) this;
        }

        public Criteria andSupporterNumberGreaterThan(Integer value) {
            addCriterion("supporter_number >", value, "supporterNumber");
            return (Criteria) this;
        }

        public Criteria andSupporterNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("supporter_number >=", value, "supporterNumber");
            return (Criteria) this;
        }

        public Criteria andSupporterNumberLessThan(Integer value) {
            addCriterion("supporter_number <", value, "supporterNumber");
            return (Criteria) this;
        }

        public Criteria andSupporterNumberLessThanOrEqualTo(Integer value) {
            addCriterion("supporter_number <=", value, "supporterNumber");
            return (Criteria) this;
        }

        public Criteria andSupporterNumberIn(List<Integer> values) {
            addCriterion("supporter_number in", values, "supporterNumber");
            return (Criteria) this;
        }

        public Criteria andSupporterNumberNotIn(List<Integer> values) {
            addCriterion("supporter_number not in", values, "supporterNumber");
            return (Criteria) this;
        }

        public Criteria andSupporterNumberBetween(Integer value1, Integer value2) {
            addCriterion("supporter_number between", value1, value2, "supporterNumber");
            return (Criteria) this;
        }

        public Criteria andSupporterNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("supporter_number not between", value1, value2, "supporterNumber");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdIsNull() {
            addCriterion("initiator_id is null");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdIsNotNull() {
            addCriterion("initiator_id is not null");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdEqualTo(Integer value) {
            addCriterion("initiator_id =", value, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdNotEqualTo(Integer value) {
            addCriterion("initiator_id <>", value, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdGreaterThan(Integer value) {
            addCriterion("initiator_id >", value, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("initiator_id >=", value, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdLessThan(Integer value) {
            addCriterion("initiator_id <", value, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("initiator_id <=", value, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdIn(List<Integer> values) {
            addCriterion("initiator_id in", values, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdNotIn(List<Integer> values) {
            addCriterion("initiator_id not in", values, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdBetween(Integer value1, Integer value2) {
            addCriterion("initiator_id between", value1, value2, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("initiator_id not between", value1, value2, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Long value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Long value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Long value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Long value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Long value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Long> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Long> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Long value1, Long value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Long value1, Long value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andFollowerCountIsNull() {
            addCriterion("follower_count is null");
            return (Criteria) this;
        }

        public Criteria andFollowerCountIsNotNull() {
            addCriterion("follower_count is not null");
            return (Criteria) this;
        }

        public Criteria andFollowerCountEqualTo(Integer value) {
            addCriterion("follower_count =", value, "followerCount");
            return (Criteria) this;
        }

        public Criteria andFollowerCountNotEqualTo(Integer value) {
            addCriterion("follower_count <>", value, "followerCount");
            return (Criteria) this;
        }

        public Criteria andFollowerCountGreaterThan(Integer value) {
            addCriterion("follower_count >", value, "followerCount");
            return (Criteria) this;
        }

        public Criteria andFollowerCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("follower_count >=", value, "followerCount");
            return (Criteria) this;
        }

        public Criteria andFollowerCountLessThan(Integer value) {
            addCriterion("follower_count <", value, "followerCount");
            return (Criteria) this;
        }

        public Criteria andFollowerCountLessThanOrEqualTo(Integer value) {
            addCriterion("follower_count <=", value, "followerCount");
            return (Criteria) this;
        }

        public Criteria andFollowerCountIn(List<Integer> values) {
            addCriterion("follower_count in", values, "followerCount");
            return (Criteria) this;
        }

        public Criteria andFollowerCountNotIn(List<Integer> values) {
            addCriterion("follower_count not in", values, "followerCount");
            return (Criteria) this;
        }

        public Criteria andFollowerCountBetween(Integer value1, Integer value2) {
            addCriterion("follower_count between", value1, value2, "followerCount");
            return (Criteria) this;
        }

        public Criteria andFollowerCountNotBetween(Integer value1, Integer value2) {
            addCriterion("follower_count not between", value1, value2, "followerCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountIsNull() {
            addCriterion("like_count is null");
            return (Criteria) this;
        }

        public Criteria andLikeCountIsNotNull() {
            addCriterion("like_count is not null");
            return (Criteria) this;
        }

        public Criteria andLikeCountEqualTo(Integer value) {
            addCriterion("like_count =", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotEqualTo(Integer value) {
            addCriterion("like_count <>", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountGreaterThan(Integer value) {
            addCriterion("like_count >", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("like_count >=", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountLessThan(Integer value) {
            addCriterion("like_count <", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountLessThanOrEqualTo(Integer value) {
            addCriterion("like_count <=", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountIn(List<Integer> values) {
            addCriterion("like_count in", values, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotIn(List<Integer> values) {
            addCriterion("like_count not in", values, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountBetween(Integer value1, Integer value2) {
            addCriterion("like_count between", value1, value2, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("like_count not between", value1, value2, "likeCount");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureIsNull() {
            addCriterion("header_picture is null");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureIsNotNull() {
            addCriterion("header_picture is not null");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureEqualTo(String value) {
            addCriterion("header_picture =", value, "headerPicture");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureNotEqualTo(String value) {
            addCriterion("header_picture <>", value, "headerPicture");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureGreaterThan(String value) {
            addCriterion("header_picture >", value, "headerPicture");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureGreaterThanOrEqualTo(String value) {
            addCriterion("header_picture >=", value, "headerPicture");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureLessThan(String value) {
            addCriterion("header_picture <", value, "headerPicture");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureLessThanOrEqualTo(String value) {
            addCriterion("header_picture <=", value, "headerPicture");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureLike(String value) {
            addCriterion("header_picture like", value, "headerPicture");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureNotLike(String value) {
            addCriterion("header_picture not like", value, "headerPicture");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureIn(List<String> values) {
            addCriterion("header_picture in", values, "headerPicture");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureNotIn(List<String> values) {
            addCriterion("header_picture not in", values, "headerPicture");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureBetween(String value1, String value2) {
            addCriterion("header_picture between", value1, value2, "headerPicture");
            return (Criteria) this;
        }

        public Criteria andHeaderPictureNotBetween(String value1, String value2) {
            addCriterion("header_picture not between", value1, value2, "headerPicture");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 30 00:02:39 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}