package com.crowdFunding.databaseProvider.model;

public class Promoter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter.id
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter.project_id
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter.name
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter.position
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter.introduction
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter.avatar
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter.id
     *
     * @return the value of promoter.id
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter.id
     *
     * @param id the value for promoter.id
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter.project_id
     *
     * @return the value of promoter.project_id
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter.project_id
     *
     * @param projectId the value for promoter.project_id
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter.name
     *
     * @return the value of promoter.name
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter.name
     *
     * @param name the value for promoter.name
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter.position
     *
     * @return the value of promoter.position
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter.position
     *
     * @param position the value for promoter.position
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter.introduction
     *
     * @return the value of promoter.introduction
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter.introduction
     *
     * @param introduction the value for promoter.introduction
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter.avatar
     *
     * @return the value of promoter.avatar
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter.avatar
     *
     * @param avatar the value for promoter.avatar
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }
}