package com.crowdFunding.databaseProvider.model;

public class TagProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_project.id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_project.project_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_project.tag_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private Integer tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_project.id
     *
     * @return the value of tag_project.id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_project.id
     *
     * @param id the value for tag_project.id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_project.project_id
     *
     * @return the value of tag_project.project_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_project.project_id
     *
     * @param projectId the value for tag_project.project_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_project.tag_id
     *
     * @return the value of tag_project.tag_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_project.tag_id
     *
     * @param tagId the value for tag_project.tag_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }
}