package com.crowdFunding.databaseProvider.model;

public class TypeProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_project.id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_project.project_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_project.type_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    private Integer typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_project.id
     *
     * @return the value of type_project.id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_project.id
     *
     * @param id the value for type_project.id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_project.project_id
     *
     * @return the value of type_project.project_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_project.project_id
     *
     * @param projectId the value for type_project.project_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_project.type_id
     *
     * @return the value of type_project.type_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_project.type_id
     *
     * @param typeId the value for type_project.type_id
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
}