package com.crowdFunding.databaseProvider.mapper;

import com.crowdFunding.databaseProvider.model.InitiatorInfo;
import com.crowdFunding.databaseProvider.model.InitiatorInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InitiatorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initiator_info
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    long countByExample(InitiatorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initiator_info
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int deleteByExample(InitiatorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initiator_info
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initiator_info
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int insert(InitiatorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initiator_info
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int insertSelective(InitiatorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initiator_info
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    List<InitiatorInfo> selectByExample(InitiatorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initiator_info
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    InitiatorInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initiator_info
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") InitiatorInfo record, @Param("example") InitiatorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initiator_info
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int updateByExample(@Param("record") InitiatorInfo record, @Param("example") InitiatorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initiator_info
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int updateByPrimaryKeySelective(InitiatorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initiator_info
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int updateByPrimaryKey(InitiatorInfo record);
}