package com.crowdFunding.databaseProvider.mapper;

import com.crowdFunding.databaseProvider.model.Promoter;
import com.crowdFunding.databaseProvider.model.PromoterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromoterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    long countByExample(PromoterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int deleteByExample(PromoterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int insert(Promoter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int insertSelective(Promoter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    List<Promoter> selectByExample(PromoterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    Promoter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") Promoter record, @Param("example") PromoterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int updateByExample(@Param("record") Promoter record, @Param("example") PromoterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int updateByPrimaryKeySelective(Promoter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int updateByPrimaryKey(Promoter record);
}