package com.crowdFunding.databaseProvider.mapper;

import com.crowdFunding.databaseProvider.model.TagProject;
import com.crowdFunding.databaseProvider.model.TagProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_project
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    long countByExample(TagProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_project
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int deleteByExample(TagProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_project
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_project
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int insert(TagProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_project
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int insertSelective(TagProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_project
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    List<TagProject> selectByExample(TagProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_project
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    TagProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_project
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") TagProject record, @Param("example") TagProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_project
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int updateByExample(@Param("record") TagProject record, @Param("example") TagProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_project
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int updateByPrimaryKeySelective(TagProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_project
     *
     * @mbg.generated Tue Feb 18 13:50:25 CST 2020
     */
    int updateByPrimaryKey(TagProject record);
}