package com.crowdFunding.databaseProvider.mapper;

import com.crowdFunding.databaseProvider.model.TypeProject;
import com.crowdFunding.databaseProvider.model.TypeProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TypeProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    long countByExample(TypeProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int deleteByExample(TypeProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int insert(TypeProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int insertSelective(TypeProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    List<TypeProject> selectByExample(TypeProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    TypeProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") TypeProject record, @Param("example") TypeProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int updateByExample(@Param("record") TypeProject record, @Param("example") TypeProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int updateByPrimaryKeySelective(TypeProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_project
     *
     * @mbg.generated Thu Jan 30 00:02:39 CST 2020
     */
    int updateByPrimaryKey(TypeProject record);
}