server:
  port: 2000
spring:
  datasource:
    url: jdbc:mysql://45.76.75.121:3306/crowd_funding?useSSL=false
    username: root
    password: Justin.171464928
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: database-provider
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
mybatis:
  type-aliases-package: com.crowdFunding.databaseProvider.model.mapper
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true