server:
  port: 80
spring:
  redis:
    cluster:
      nodes: 149.248.18.111:9920,149.248.18.111:9921,149.248.18.111:9922,149.248.18.111:9923,149.248.18.111:9924,149.248.18.111:9925
      max-redirects: 3
    password: justin.171464928
    jedis:
      pool:
        max-idle: 100
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
rocketmq:
  name-server: 45.76.175.197:19876;45.76.175.197:29876
  producer:
    group: ChunkFileUploadGroup
    send-message-timeout: 6000
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://45.32.64.240:8761/eureka/
  instance:
    prefer-ip-address: true

